### ISSUE TITLE
Cannot render image with 10000 pixels plus

### ISSUE THREAD

**Issue by vmakovsky** [MrP/phantomjs-render-large-page#1]
Using phantomjs 2.1.1, phantomjs-render-large-page 0.3.1,
the following script renders png if width is 8000 but not if it's 10000 or more:

```
    var renderLargePage = require("phantomjs-render-large-page").renderLargePage;
    var page = require("webpage").create();
    page.viewportSize = { width:8020,height:5020 };
    page.clipRect = { width:8000,height:5000,left:10,top:10 };
    page.open("file:///home/v/test.html", function () {
        renderLargePage(page, "test.png", function (error) {
            phantom.exit();
        })
    });
```

It's even less than with normal phantomjs. It also gives me always this error:
Blocked a frame with origin "file://" from accessing a frame with origin "null".  The frame requesting access has a protocol of "file", the frame being accessed has a protocol of "about". Protocols must match.

But it doesn't seem to have an effect on rendering.
What might be wrong?

**Comment by MrP** [comment]
Hi @vmakovsky,
Thanks for the feedback!
Now let's see:
- From the error you mention, seems lilke you have an iframe in your test.html that phantomJS doesn't like.  It could be that PhantomJS implements the same origin policy for iframes+file:// URLs a bit different than other browsers, I really don't know.  I know browsers are especially strict with local URLs, as it's a potential security issue.

- Setting the viewportSize to such a big number shouldn't be necessary if you just want to render the whole page.  For example, with your values, that's the equivalent of having a browser window that is 8000x4000.  That's kind of a big window :) It's entirely possible that phantomJS is running out of memory or cannot handle it in some way.  I just did a couple of tests in a VM and I can't even get to that size.

- Setting the `clipRect` is unfortunately not supported at this time by `phantomjs-render-large-page`. `renderLargePage` sets it internally to render the pieces itself, so it will do nothing. (I haven't tested that)

So, I would try again without setting viewportSize or clipRect.  About the iframe issue, I don't know, but you could try to serve the file with some simple http server instead of loading it directly as file://.

Hope that helps!

**Comment by vmakovsky** [comment]
Hi Victor,

Thanks for your hints. I tried it on Fedora 24 and it doesn't give the warning.
I got warnings debian 8.6. I changed imagemagick for st. compatible.
I think I was getting warning even for simple html page - but it has no influence
on rendering. 

Now on both system I can get max. image of 256M pixels.
It's the same with or without using the plugin.
There seems to be also a limit on the image width - I could get 32k at most
after that the image had transparent background.

You are right about the viewport. 
I ran firefox - and I can get 23k x 23k big image.

From cmd line it looks to be a some problem with library limitation
in the page - jquery + leaflet + leaflet heat.

From within browser, it looks like I start hitting some system limitation -
e.g. timeouts.

So looks not an error of the library. Is that 32k width limitation of phantomjs (firefox)
any way to get around that?

**Comment by MrP** [comment]
Sorry, I don't know.  For really tall and wide images at some point the machine eventually runs out of memory :P

**Comment by vmakovsky** [comment]
What is the difference between PhantomJS and this plugin when taking pictures?

**Comment by MrP** [comment]
If you try to render a web page 1000px wide and 60000px tall, PhantomJS will only render the first 30000px.
My library helps with that.  I don't know what issue specifically you're having with PhantomJHS, but it sounds like this library won't help you, sorry.
